# Generated by Django 3.0.5 on 2020-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS_NO', models.FloatField(blank=True, db_column='PS NO', null=True)),
                ('Name', models.CharField(blank=True, max_length=2555, null=True)),
                ('Grade', models.CharField(blank=True, max_length=2555, null=True)),
                ('Dept_Loc', models.CharField(blank=True, max_length=2555, null=True)),
                ('Billed_status', models.CharField(blank=True, max_length=2555, null=True)),
                ('Skill', models.CharField(blank=True, max_length=2555, null=True)),
                ('Action_Category', models.CharField(blank=True, max_length=2555, null=True)),
                ('Action_Sub_Category', models.CharField(blank=True, max_length=2555, null=True)),
                ('Active_Account', models.CharField(blank=True, max_length=2555, null=True)),
                ('Proposed_Accounts', models.CharField(blank=True, max_length=2555, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=2555, null=True)),
                ('Selected_Date', models.DateField(blank=True, null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=2555, null=True)),
                ('Release_To_PU_Date', models.DateField(blank=True, null=True)),
                ('Start_Date', models.DateField(blank=True, null=True)),
                ('End_Date', models.DateField(blank=True, null=True)),
                ('Unbilled_Age_In_Current_BU', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.FloatField(blank=True, null=True)),
                ('Aging_Bucket', models.CharField(blank=True, max_length=2555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.CharField(max_length=3000),
        ),
    ]
