# Generated by Django 3.0.5 on 2020-04-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200406_0513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DP',
            new_name='Deployable_Pool',
        ),
    ]
