# Generated by Django 3.0.5 on 2020-04-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_academy_manpower_rotation_rrdump'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deployable_Pool',
        ),
    ]
