# Generated by Django 3.0.5 on 2020-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_deployable_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployable_Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PSNO', models.FloatField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=2555, null=True)),
                ('Grade', models.CharField(blank=True, max_length=2555, null=True)),
                ('DeptLoc', models.CharField(blank=True, max_length=2555, null=True, verbose_name='Dept Loc')),
                ('Billedstatus', models.CharField(blank=True, max_length=2555, null=True)),
                ('Skill', models.CharField(blank=True, max_length=2555, null=True)),
                ('ActionCategory', models.CharField(blank=True, max_length=2555, null=True)),
                ('ActionSubCategory', models.CharField(blank=True, max_length=2555, null=True)),
                ('ActiveAccount', models.CharField(blank=True, max_length=2555, null=True)),
                ('ProposedAccounts', models.CharField(blank=True, max_length=2555, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=2555, null=True)),
                ('SelectedDate', models.DateField(blank=True, null=True)),
                ('CustomerName', models.CharField(blank=True, max_length=2555, null=True)),
                ('ReleaseToPUDate', models.DateField(blank=True, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('UnbilledAgeInCurrentBU', models.IntegerField(blank=True, null=True)),
                ('Mobile', models.FloatField(blank=True, null=True)),
                ('AgingBucket', models.CharField(blank=True, max_length=2555, null=True)),
            ],
        ),
    ]
