# Generated by Django 3.0.5 on 2020-04-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_deployable_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rrdump',
            old_name='Customer_Name',
            new_name='BilledStatus',
        ),
        migrations.AddField(
            model_name='rrdump',
            name='BillingEndDate',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='BillingStartDate',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='ClientLoc',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='DeliveryBU',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='Description',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='DesiredSkill',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='JobDescription',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='Location',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='MandatorySkill',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='NeedByDate',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='NoOfPos',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='OpportunityID',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='ProjectID',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='ProposeID',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='RR',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='RRSno',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='RRno',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AddField(
            model_name='rrdump',
            name='Status',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.AlterField(
            model_name='deployable_pool',
            name='PSNO',
            field=models.FloatField(blank=True, default='PS NO', null=True),
        ),
    ]
