# Generated by Django 3.0.5 on 2020-04-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200407_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image_url',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Stock',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Price',
            new_name='RollNo',
        ),
    ]
