# Generated by Django 3.0.5 on 2020-04-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200407_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployable_pool',
            name='Mobile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
